name: 'Infra_build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
    Dev_Plan:
        uses: littleworks-inc/gcp-infra/.github/workflows/terraform-pan.yml@main
        with:
            path: .
            tf_version: latest
            gcp_backend_bucket: gcp-gitlab-ci-demo-01
            gcp_backend_bucket_prefix: terraform
            tf_vars_file: dev.tfvars 
            enable_TFSEC: true 
        secrets:
            workload_identity_provider: ${{ secrets.workload_identity_provider }}
            service_account: ${{ secrets.service_account }}
            # environment: dev
        permissions:
          contents: 'read'
          id-token: 'write'

    Dev_Deploy:
        needs: Dev_Plan
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: littleworks-inc/gcp-infra/.github/workflows/terraform-apply.yml@main
        with:
            path: .
            tf_version: latest
            gcp_backend_bucket: gcp-gitlab-ci-demo-01
            gcp_backend_bucket_prefix: terraform
            tf_vars_file: dev.tfvars 
        secrets:
            workload_identity_provider: ${{ secrets.workload_identity_provider }}
            service_account: ${{ secrets.service_account }}
            # environment: dev
        permissions:
            contents: 'read'
            id-token: 'write'