name: 'Infra_build'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
    Dev_Plan:
        uses: littleworks-inc/gcp-infra/.github/workflows/terraform-pan.yml@main
        with:
            path: .
            tf_version: latest
            gcp_backend_bucket: gcp-gitlab-ci-demo-01
            gcp_backend_bucket_prefix: terraform
            tf_vars_file: dev.tfvars 
            enable_TFSEC: true 
            workload_identity_provider: 'projects/$428136795394/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
            service_account: 'gcp-workload-identity@nomadic-rush-408023.iam.gserviceaccount.com'
            # PROJECT_ID: "nomadic-rush-408023"
            # PROJECT_NO: "428136795394"
            # environment: dev
        permissions:
          contents: 'read'
          id-token: 'write'

    Dev_Deploy:
        needs: Dev_Plan
        uses: littleworks-inc/gcp-infra/.github/workflows/terraform-apply.yml@main
        with:
            path: .
            tf_version: latest
            gcp_backend_bucket: gcp-gitlab-ci-demo-01
            gcp_backend_bucket_prefix: terraform
            tf_vars_file: dev.tfvars 
            workload_identity_provider: 'projects/$428136795394/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
            service_account: 'gcp-workload-identity@nomadic-rush-408023.iam.gserviceaccount.com'
            # PROJECT_ID: "nomadic-rush-408023"
            # PROJECT_NO: "428136795394"
            # environment: dev
        permissions:
            contents: 'read'
            id-token: 'write'