on:
  workflow_call:
    inputs:
      path:
        description: "Terraform Root Path"
        required: true
        type: string
      tf_version:
        description: 'Terraform Version. e.g: 1.3.0 Default=latest.'
        required: false
        type: string
        default: latest
      tf_vars_file:
        description: 'Terraform TFVARS file name.'
        required: true
        type: string
      gcp_backend_bucket:
        description: 'GCP Storage bucket name to store terraform state file.'
        required: true
        type: string
      gcp_backend_bucket_prefix:
        description: 'GCP Storage bucket folder name to store terraform state file.'
        required: true
        type: string
      # environment:
      #   description: 'manual approvals in GitHub Actions with the Environments.'
      #   required: true
      #   type: string

jobs:
  build-apply:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment }}
    
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}

    env:
      bucket_name: ${{ inputs.gcp_backend_bucket }}
      bucket_prefix: ${{ inputs.gcp_backend_bucket_prefix }}
      PROJECT_ID: "nomadic-rush-408023"
      PROJECT_NO: "428136795394"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        # create_credentials_file: 'true'
        workload_identity_provider: 'projects/${{env.PROJECT_NO}}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'gcp-workload-identity@${{env.PROJECT_ID}}.iam.gserviceaccount.com'

    - name: Download Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: ${{ inputs.gcp_backend_bucket_prefix }}
        path: ${{ inputs.path }}

    - name: Decompress TF Plan artifact
      run: echo "y" | unzip -o ${{ inputs.gcp_backend_bucket_prefix }}.zip
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf_version }}
    
    - name: Terraform Init
      run: terraform init --backend-config="bucket=$bucket_name" --backend-config="prefix=$bucket_prefix"

    # - name: Terraform Apply
    #   run: terraform apply plan.tfplan 